"""add pms tables

Revision ID: 0ec87e27af49
Revises: 25dd2af84bb2
Create Date: 2026-07-30 08:17:28.772622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec87e27af49'
down_revision: Union[str, Sequence[str], None] = '25dd2af84bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competencies_company_id'), 'competencies', ['company_id'], unique=False)
    op.create_table('rating_scales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('descriptors_json', sa.JSON(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_scales_company_id'), 'rating_scales', ['company_id'], unique=False)
    op.create_table('pms_review_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_role', sa.Enum('SELF', 'MANAGER', 'PEER', 'SUBORDINATE', name='pms_reviewer_role'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='pms_review_request_status'), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['appraisal_cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_review_requests_cycle_id'), 'pms_review_requests', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_pms_review_requests_employee_id'), 'pms_review_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_pms_review_requests_reviewer_user_id'), 'pms_review_requests', ['reviewer_user_id'], unique=False)
    op.create_table('promotion_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('recommended_by', sa.Integer(), nullable=False),
    sa.Column('recommended_designation_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='promotion_recommendation_status'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['appraisal_cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['recommended_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recommended_designation_id'], ['designations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_recommendations_cycle_id'), 'promotion_recommendations', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_promotion_recommendations_employee_id'), 'promotion_recommendations', ['employee_id'], unique=False)
    op.create_table('pms_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_role', sa.Enum('SELF', 'MANAGER', 'PEER', 'SUBORDINATE', name='pms_reviewer_role'), nullable=False),
    sa.Column('review_request_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['appraisal_cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['review_request_id'], ['pms_review_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_request_id')
    )
    op.create_index(op.f('ix_pms_evaluations_cycle_id'), 'pms_evaluations', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_pms_evaluations_employee_id'), 'pms_evaluations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_pms_evaluations_evaluator_id'), 'pms_evaluations', ['evaluator_id'], unique=False)
    op.create_table('pms_evaluation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['pms_evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_evaluation_items_evaluation_id'), 'pms_evaluation_items', ['evaluation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pms_evaluation_items_evaluation_id'), table_name='pms_evaluation_items')
    op.drop_table('pms_evaluation_items')
    op.drop_index(op.f('ix_pms_evaluations_evaluator_id'), table_name='pms_evaluations')
    op.drop_index(op.f('ix_pms_evaluations_employee_id'), table_name='pms_evaluations')
    op.drop_index(op.f('ix_pms_evaluations_cycle_id'), table_name='pms_evaluations')
    op.drop_table('pms_evaluations')
    op.drop_index(op.f('ix_promotion_recommendations_employee_id'), table_name='promotion_recommendations')
    op.drop_index(op.f('ix_promotion_recommendations_cycle_id'), table_name='promotion_recommendations')
    op.drop_table('promotion_recommendations')
    op.drop_index(op.f('ix_pms_review_requests_reviewer_user_id'), table_name='pms_review_requests')
    op.drop_index(op.f('ix_pms_review_requests_employee_id'), table_name='pms_review_requests')
    op.drop_index(op.f('ix_pms_review_requests_cycle_id'), table_name='pms_review_requests')
    op.drop_table('pms_review_requests')
    op.drop_index(op.f('ix_rating_scales_company_id'), table_name='rating_scales')
    op.drop_table('rating_scales')
    op.drop_index(op.f('ix_competencies_company_id'), table_name='competencies')
    op.drop_table('competencies')
    # ### end Alembic commands ###
