"""add employee bank details and profile photo

Revision ID: 12df50a187f5
Revises: f8bc05f58131
Create Date: 2026-07-29 22:26:52.866094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12df50a187f5'
down_revision: Union[str, Sequence[str], None] = 'f8bc05f58131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('bank_account_holder_name', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('bank_branch_name', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('bank_account_type', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('profile_photo_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'profile_photo_path')
    op.drop_column('employees', 'bank_account_type')
    op.drop_column('employees', 'bank_branch_name')
    op.drop_column('employees', 'bank_account_holder_name')
    # ### end Alembic commands ###
