"""add sprints and board fields

Revision ID: 15997c9a9abe
Revises: e5afe19a9667
Create Date: 2026-08-20 20:43:11.311336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15997c9a9abe'
down_revision: Union[str, Sequence[str], None] = 'e5afe19a9667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('sprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('FUTURE', 'ACTIVE', 'COMPLETED', 'CLOSED', name='sprint_status'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprints_project_id'), 'sprints', ['project_id'], unique=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_statuses', sa.Column('wip_limit', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('sprint_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('board_position', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('tickets', 'board_position', server_default=None)
    op.create_index(op.f('ix_tickets_sprint_id'), 'tickets', ['sprint_id'], unique=False)
    op.create_foreign_key(None, 'tickets', 'sprints', ['sprint_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_sprint_id'), table_name='tickets')
    op.drop_column('tickets', 'board_position')
    op.drop_column('tickets', 'sprint_id')
    op.drop_column('ticket_statuses', 'wip_limit')
    # ### end Alembic commands ###

    op.drop_index(op.f('ix_sprints_project_id'), table_name='sprints')
    op.drop_table('sprints')
