"""add appraisal cycles and kra tables

Revision ID: 25dd2af84bb2
Revises: 8b458916fdb4
Create Date: 2026-07-30 07:48:59.083999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25dd2af84bb2'
down_revision: Union[str, Sequence[str], None] = '8b458916fdb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appraisal_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', name='appraisal_cycle_status'), nullable=False),
    sa.Column('review_stages_json', sa.JSON(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appraisal_cycles_company_id'), 'appraisal_cycles', ['company_id'], unique=False)
    op.create_table('kra_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kra_templates_company_id'), 'kra_templates', ['company_id'], unique=False)
    op.create_table('kra_template_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_weightage', sa.Float(), nullable=False),
    sa.Column('measurement_criteria', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['kra_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kra_template_items_template_id'), 'kra_template_items', ['template_id'], unique=False)
    op.create_table('employee_kras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'REVIEWED', 'APPROVED', name='kra_status'), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['appraisal_cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['kra_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_kras_cycle_id'), 'employee_kras', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_employee_kras_employee_id'), 'employee_kras', ['employee_id'], unique=False)
    op.create_table('employee_kra_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_kra_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weightage', sa.Float(), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('employee_rating', sa.Float(), nullable=True),
    sa.Column('employee_comment', sa.Text(), nullable=True),
    sa.Column('manager_rating', sa.Float(), nullable=True),
    sa.Column('manager_comment', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['employee_kra_id'], ['employee_kras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_kra_items_employee_kra_id'), 'employee_kra_items', ['employee_kra_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_kra_items_employee_kra_id'), table_name='employee_kra_items')
    op.drop_table('employee_kra_items')
    op.drop_index(op.f('ix_employee_kras_employee_id'), table_name='employee_kras')
    op.drop_index(op.f('ix_employee_kras_cycle_id'), table_name='employee_kras')
    op.drop_table('employee_kras')
    op.drop_index(op.f('ix_kra_template_items_template_id'), table_name='kra_template_items')
    op.drop_table('kra_template_items')
    op.drop_index(op.f('ix_kra_templates_company_id'), table_name='kra_templates')
    op.drop_table('kra_templates')
    op.drop_index(op.f('ix_appraisal_cycles_company_id'), table_name='appraisal_cycles')
    op.drop_table('appraisal_cycles')
    # ### end Alembic commands ###
