"""add employee module access override

Revision ID: 6e43312d8be5
Revises: 0ec87e27af49
Create Date: 2026-07-30 11:00:29.606591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e43312d8be5'
down_revision: Union[str, Sequence[str], None] = '0ec87e27af49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('module_access_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'module_access_json')
    # ### end Alembic commands ###
