"""add project capacity schedule fields

Revision ID: 76ef783ac758
Revises: 37096bb64c19
Create Date: 2026-09-01 08:11:14.061067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ef783ac758'
down_revision: Union[str, Sequence[str], None] = '37096bb64c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('projects', sa.Column('hours_per_day', sa.Float(), nullable=False, server_default='8'))
    op.add_column(
        'projects',
        sa.Column('working_days', sa.JSON(), nullable=False, server_default='[0, 1, 2, 3, 4]'),
    )
    op.alter_column('projects', 'hours_per_day', server_default=None)
    op.alter_column('projects', 'working_days', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'working_days')
    op.drop_column('projects', 'hours_per_day')
    # ### end Alembic commands ###
