"""Add activity tracker models

Revision ID: b1417e9065fd
Revises: 6e43312d8be5
Create Date: 2026-08-04 17:12:49.662842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1417e9065fd'
down_revision: Union[str, Sequence[str], None] = '6e43312d8be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_categories_company_id'), 'activity_categories', ['company_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('time_block', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_overtime', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['activity_categories.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_category_id'), 'activity_logs', ['category_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_employee_id'), 'activity_logs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_log_date'), 'activity_logs', ['log_date'], unique=False)
    op.create_table('team_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'manager_id', name='uq_team_mapping_emp_mgr')
    )
    op.create_index(op.f('ix_team_mappings_company_id'), 'team_mappings', ['company_id'], unique=False)
    op.create_index(op.f('ix_team_mappings_employee_id'), 'team_mappings', ['employee_id'], unique=False)
    op.create_index(op.f('ix_team_mappings_manager_id'), 'team_mappings', ['manager_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_mappings_manager_id'), table_name='team_mappings')
    op.drop_index(op.f('ix_team_mappings_employee_id'), table_name='team_mappings')
    op.drop_index(op.f('ix_team_mappings_company_id'), table_name='team_mappings')
    op.drop_table('team_mappings')
    op.drop_index(op.f('ix_activity_logs_log_date'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_employee_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_category_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_activity_categories_company_id'), table_name='activity_categories')
    op.drop_table('activity_categories')
    # ### end Alembic commands ###
