"""add reporting manager and leave management tables

Revision ID: b93628946a3d
Revises: 12df50a187f5
Create Date: 2026-07-29 23:09:49.575569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93628946a3d'
down_revision: Union[str, Sequence[str], None] = '12df50a187f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('max_days_per_year', sa.Float(), nullable=False),
    sa.Column('carry_forward_allowed', sa.Boolean(), nullable=False),
    sa.Column('max_carry_forward_days', sa.Float(), nullable=True),
    sa.Column('encashment_allowed', sa.Boolean(), nullable=False),
    sa.Column('is_unpaid', sa.Boolean(), nullable=False),
    sa.Column('color_code', sa.String(length=7), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_types_company_id'), 'leave_types', ['company_id'], unique=False)
    op.create_table('leave_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('attachment_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING_MANAGER', 'PENDING_HR', 'APPROVED', 'REJECTED', 'CANCELLED', name='leave_application_status'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('manager_action_by', sa.Integer(), nullable=True),
    sa.Column('manager_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hr_action_by', sa.Integer(), nullable=True),
    sa.Column('hr_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['hr_action_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.ForeignKeyConstraint(['manager_action_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_applications_employee_id'), 'leave_applications', ['employee_id'], unique=False)
    op.create_table('leave_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_allocated', sa.Float(), nullable=False),
    sa.Column('used', sa.Float(), nullable=False),
    sa.Column('carried_forward', sa.Float(), nullable=False),
    sa.Column('encashed', sa.Float(), nullable=False),
    sa.Column('lapsed', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'leave_type_id', 'year', name='uq_leave_balance_employee_type_year')
    )
    op.create_index(op.f('ix_leave_balances_employee_id'), 'leave_balances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_balances_leave_type_id'), 'leave_balances', ['leave_type_id'], unique=False)
    op.create_table('leave_approval_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_application_id', sa.Integer(), nullable=False),
    sa.Column('action_by', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('SUBMITTED', 'MANAGER_APPROVED', 'MANAGER_REJECTED', 'HR_APPROVED', 'HR_REJECTED', 'CANCELLED', name='leave_approval_action'), nullable=False),
    sa.Column('action_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['action_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['leave_application_id'], ['leave_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_approval_history_leave_application_id'), 'leave_approval_history', ['leave_application_id'], unique=False)
    op.add_column('employees', sa.Column('reporting_manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'employees', ['reporting_manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'reporting_manager_id')
    op.drop_index(op.f('ix_leave_approval_history_leave_application_id'), table_name='leave_approval_history')
    op.drop_table('leave_approval_history')
    op.drop_index(op.f('ix_leave_balances_leave_type_id'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_employee_id'), table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index(op.f('ix_leave_applications_employee_id'), table_name='leave_applications')
    op.drop_table('leave_applications')
    op.drop_index(op.f('ix_leave_types_company_id'), table_name='leave_types')
    op.drop_table('leave_types')
    # ### end Alembic commands ###
