"""add sprint committed points

Revision ID: bc9a9f23edb6
Revises: 15997c9a9abe
Create Date: 2026-08-20 20:58:24.041686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc9a9f23edb6'
down_revision: Union[str, Sequence[str], None] = '15997c9a9abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('committed_points', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('sprints', 'committed_points', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprints', 'committed_points')
    # ### end Alembic commands ###
