"""add review_notes to employee_documents

Revision ID: f8bc05f58131
Revises: a54dab39d83a
Create Date: 2026-07-29 22:10:51.258454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8bc05f58131'
down_revision: Union[str, Sequence[str], None] = 'a54dab39d83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_departments_head_employee_id', 'departments', 'employees', ['head_employee_id'], ['id'], use_alter=True)
    op.add_column('employee_documents', sa.Column('review_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_documents', 'review_notes')
    op.drop_constraint('fk_departments_head_employee_id', 'departments', type_='foreignkey')
    # ### end Alembic commands ###
